from argparse import ArgumentParser


def parse_args():
    parser = ArgumentParser()
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--cuda", type=bool, default=False, nargs='?', const=True)
    parser.add_argument("--cudnn", type=bool, default=False, nargs='?', const=True)
    parser.add_argument("--debug", type=bool, default=True, nargs='?', const=True)
    parser.add_argument("--distance_type", type=str, default="euclidean")
    parser.add_argument("--finetune", type=bool, default=True, nargs='?', const=True)
    parser.add_argument("--flip", type=bool, default=False, nargs='?', const=True)
    parser.add_argument("--gpu", type=int)
    parser.add_argument("--image_dir", type=str, default="/afs/crc/group/cvrl/czajka/gbir2/aczajka/BXGRID/iris_segmented_SegNet")
    parser.add_argument("--img_uid_map", type=str, default="img_to_uid_map.json")
    parser.add_argument("--log_batch", type=int, default=10)
    parser.add_argument("--log_txt", type=bool, default=True, nargs='?', const=True)
    parser.add_argument("--lr", type=float, default=0.00001)
    parser.add_argument("--margin", type=float, default=None)
    parser.add_argument("--mode", default="train")
    parser.add_argument("--model_type", type=str, default="convnext_tiny")
    parser.add_argument("--multi_gpu", type=bool, default=False, nargs='?', const=True)
    parser.add_argument("--num_epochs", type=int, default=2001)
    parser.add_argument("--num_workers", type=int, default=2)
    parser.add_argument("--polar", type=bool, default=True, nargs='?', const=True)
    parser.add_argument("--state")
    parser.add_argument("--stem_width", type=int, default=64)
    parser.add_argument("--tag", type=str, default="")
    parser.add_argument("--val_image_dir", default=None)
    parser.add_argument("--val_img_uid_map", default=None)
    return parser.parse_args()
